server:
  port: 9528
  ssl:
    key-store: classpath:ailuoli.cn.jks
    key-store-password: i12yn725y20q
    key-store-type: JKS
    enabled: true

knife4j:
  enable: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.234.127:1234/psychology?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: bingyue
    password: bingyue
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      # 默认 800
      max-lifetime: 30000
      connection-test-query: SELECT 1
  redis:
    port: 1235
    host: 120.53.234.127
    password: lby123456
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 526518441@qq.com
#    password: kclrhjpacblididg
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
    test-connection: false
    valicode:
      expired: 300
    password: mmabrxnycmzabgjg
  security:
    remember:
      # 两周
      timeout: "1209600"
minio:
  endpoint: https://ailuoli.cn:9000
  domain: https://ailuoli.cn:9000
  accessKey: a0/v2tunfHEfdgx78hXKPgldrfb5vSR7Ftnl3C
  secretKey: a0cnBv/d1PbvCfU764M.XFuYu/tSAWquUM4O6iC0cwUYPoNu0SbYWO
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lby.psychology.model
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-dialect: true
logging:
  level:
    root: info

