server:
  port: 9527
knife4j:
  enable: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.234.127:1234/psychology?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: bingyue
    password: bingyue
  redis:
    port: 1235
    host: 120.53.234.127
    password: lby123456
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 526518441@qq.com
#    password: kclrhjpacblididg
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
    test-connection: false
    valicode:
      expired: 300
    password: mmabrxnycmzabgjg

  security:
    remember:
      # 两周
      timeout: "1209600"
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lby.psychology.model
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: debug

